// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyAcademy.Data;

#nullable disable

namespace MyAcademy.Migrations
{
    [DbContext(typeof(MyAcademyContext))]
    [Migration("20260918225823_FixDisciplineIdType")]
    partial class FixDisciplineIdType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompleteDiscipline", b =>
                {
                    b.Property<int>("group")
                        .HasColumnType("int");

                    b.Property<short>("discipline")
                        .HasColumnType("smallint");

                    b.HasKey("group", "discipline");

                    b.HasIndex("discipline");

                    b.ToTable("CompleteDisciplines", (string)null);
                });

            modelBuilder.Entity("DependentDiscipline", b =>
                {
                    b.Property<short>("discipline")
                        .HasColumnType("smallint");

                    b.Property<short>("dependent_discipline")
                        .HasColumnType("smallint");

                    b.HasKey("discipline", "dependent_discipline");

                    b.HasIndex("dependent_discipline");

                    b.ToTable("DependentDisciplines", (string)null);
                });

            modelBuilder.Entity("DisciplinesDirectionsRelation", b =>
                {
                    b.Property<byte>("direction")
                        .HasColumnType("tinyint");

                    b.Property<short>("discipline")
                        .HasColumnType("smallint");

                    b.HasKey("direction", "discipline");

                    b.HasIndex("discipline");

                    b.ToTable("DisciplinesDirectionsRelation", (string)null);
                });

            modelBuilder.Entity("MyAcademy.Models.Attendance", b =>
                {
                    b.Property<int>("student")
                        .HasColumnType("int");

                    b.Property<long>("lesson")
                        .HasColumnType("bigint");

                    b.Property<bool>("present")
                        .HasColumnType("bit");

                    b.HasKey("student", "lesson");

                    b.HasIndex("lesson");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("MyAcademy.Models.DaysOFF", b =>
                {
                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<byte>("holiday")
                        .HasColumnType("tinyint");

                    b.HasKey("date")
                        .HasName("PK__DaysOFF__D9DE21FC823630A5");

                    b.HasIndex("holiday");

                    b.ToTable("DaysOFF", (string)null);
                });

            modelBuilder.Entity("MyAcademy.Models.Direction", b =>
                {
                    b.Property<byte>("direction_id")
                        .HasColumnType("tinyint");

                    b.Property<string>("direction_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("direction_id");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("MyAcademy.Models.Discipline", b =>
                {
                    b.Property<short>("discipline_id")
                        .HasColumnType("smallint");

                    b.Property<string>("discipline_name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("number_of_lessons")
                        .HasColumnType("int");

                    b.HasKey("discipline_id");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("MyAcademy.Models.Exam", b =>
                {
                    b.Property<int>("student")
                        .HasColumnType("int");

                    b.Property<short>("discipline")
                        .HasColumnType("smallint");

                    b.Property<DateOnly?>("date")
                        .HasColumnType("date");

                    b.Property<byte?>("grade")
                        .HasColumnType("tinyint");

                    b.HasKey("student", "discipline");

                    b.HasIndex("discipline");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("MyAcademy.Models.Grade", b =>
                {
                    b.Property<int>("student")
                        .HasColumnType("int");

                    b.Property<long>("lesson")
                        .HasColumnType("bigint");

                    b.Property<byte?>("grade_1")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("grade_2")
                        .HasColumnType("tinyint");

                    b.HasKey("student", "lesson")
                        .HasName("PK_Grades_1");

                    b.HasIndex("lesson");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("MyAcademy.Models.Group", b =>
                {
                    b.Property<int>("group_id")
                        .HasColumnType("int");

                    b.Property<byte>("direction")
                        .HasColumnType("tinyint");

                    b.Property<string>("group_name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("start_date")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("start_time")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<byte?>("weekdays")
                        .HasColumnType("tinyint");

                    b.HasKey("group_id");

                    b.HasIndex("direction");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("MyAcademy.Models.Holiday", b =>
                {
                    b.Property<byte>("holiday_id")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("day")
                        .HasColumnType("tinyint");

                    b.Property<byte>("duration")
                        .HasColumnType("tinyint");

                    b.Property<string>("holiday_name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte?>("month")
                        .HasColumnType("tinyint");

                    b.HasKey("holiday_id")
                        .HasName("PK__Holidays__253884EA4E99B67A");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("MyAcademy.Models.Salary", b =>
                {
                    b.Property<long>("payment_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("accrued")
                        .HasColumnType("smallmoney");

                    b.Property<bool>("received")
                        .HasColumnType("bit");

                    b.Property<short>("teacher")
                        .HasColumnType("smallint");

                    b.HasKey("payment_id")
                        .HasName("PK__Salary__ED1FC9EAA493E1B2");

                    b.HasIndex("teacher");

                    b.ToTable("Salary", (string)null);
                });

            modelBuilder.Entity("MyAcademy.Models.Schedule", b =>
                {
                    b.Property<long>("lesson_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("lesson_id"));

                    b.Property<DateOnly?>("date")
                        .HasColumnType("date");

                    b.Property<short>("discipline")
                        .HasColumnType("smallint");

                    b.Property<int>("group")
                        .HasColumnType("int");

                    b.Property<bool>("spent")
                        .HasColumnType("bit");

                    b.Property<short>("teacher")
                        .HasColumnType("smallint");

                    b.Property<TimeOnly?>("time")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.HasKey("lesson_id");

                    b.HasIndex("discipline");

                    b.HasIndex("group");

                    b.HasIndex("teacher");

                    b.ToTable("Schedule", (string)null);
                });

            modelBuilder.Entity("MyAcademy.Models.Student", b =>
                {
                    b.Property<int>("stud_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stud_id"));

                    b.Property<DateOnly>("birth_date")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("group")
                        .HasColumnType("int");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("middle_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("phone")
                        .HasMaxLength(16)
                        .HasColumnType("nchar(16)")
                        .IsFixedLength();

                    b.Property<byte[]>("photo")
                        .HasColumnType("image");

                    b.HasKey("stud_id");

                    b.HasIndex("group");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("MyAcademy.Models.Teacher", b =>
                {
                    b.Property<short>("teacher_id")
                        .HasColumnType("smallint");

                    b.Property<DateOnly?>("birth_date")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("first_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("last_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("middle_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("phone")
                        .HasMaxLength(16)
                        .HasColumnType("nchar(16)")
                        .IsFixedLength();

                    b.Property<byte[]>("photo")
                        .HasColumnType("image");

                    b.Property<decimal?>("rate")
                        .HasColumnType("smallmoney");

                    b.Property<DateOnly?>("work_since")
                        .HasColumnType("date");

                    b.HasKey("teacher_id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("RequiredDiscipline", b =>
                {
                    b.Property<short>("discipline")
                        .HasColumnType("smallint");

                    b.Property<short>("required_discipline")
                        .HasColumnType("smallint");

                    b.HasKey("discipline", "required_discipline");

                    b.HasIndex("required_discipline");

                    b.ToTable("RequiredDisciplines", (string)null);
                });

            modelBuilder.Entity("TeachersDisciplinesRelation", b =>
                {
                    b.Property<short>("teacher")
                        .HasColumnType("smallint");

                    b.Property<short>("discipline")
                        .HasColumnType("smallint");

                    b.HasKey("teacher", "discipline");

                    b.HasIndex("discipline");

                    b.ToTable("TeachersDisciplinesRelation", (string)null);
                });

            modelBuilder.Entity("CompleteDiscipline", b =>
                {
                    b.HasOne("MyAcademy.Models.Discipline", null)
                        .WithMany()
                        .HasForeignKey("discipline")
                        .IsRequired()
                        .HasConstraintName("FK_CompleteDisciplines_Disciplines");

                    b.HasOne("MyAcademy.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("group")
                        .IsRequired()
                        .HasConstraintName("FK_CompleteDisciplines_Groups");
                });

            modelBuilder.Entity("DependentDiscipline", b =>
                {
                    b.HasOne("MyAcademy.Models.Discipline", null)
                        .WithMany()
                        .HasForeignKey("dependent_discipline")
                        .IsRequired()
                        .HasConstraintName("FK_DependentDisciplines_Disciplines1");

                    b.HasOne("MyAcademy.Models.Discipline", null)
                        .WithMany()
                        .HasForeignKey("discipline")
                        .IsRequired()
                        .HasConstraintName("FK_DependentDisciplines_Disciplines");
                });

            modelBuilder.Entity("DisciplinesDirectionsRelation", b =>
                {
                    b.HasOne("MyAcademy.Models.Direction", null)
                        .WithMany()
                        .HasForeignKey("direction")
                        .IsRequired()
                        .HasConstraintName("FK_DisciplinesDirectionsRelation_Directions");

                    b.HasOne("MyAcademy.Models.Discipline", null)
                        .WithMany()
                        .HasForeignKey("discipline")
                        .IsRequired()
                        .HasConstraintName("FK_DisciplinesDirectionsRelation_Disciplines");
                });

            modelBuilder.Entity("MyAcademy.Models.Attendance", b =>
                {
                    b.HasOne("MyAcademy.Models.Schedule", "lessonNavigation")
                        .WithMany("Attendances")
                        .HasForeignKey("lesson")
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Schedule");

                    b.HasOne("MyAcademy.Models.Student", "studentNavigation")
                        .WithMany("Attendances")
                        .HasForeignKey("student")
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Students");

                    b.Navigation("lessonNavigation");

                    b.Navigation("studentNavigation");
                });

            modelBuilder.Entity("MyAcademy.Models.DaysOFF", b =>
                {
                    b.HasOne("MyAcademy.Models.Holiday", "holidayNavigation")
                        .WithMany("DaysOFFs")
                        .HasForeignKey("holiday")
                        .IsRequired()
                        .HasConstraintName("FK_DO_Holidays");

                    b.Navigation("holidayNavigation");
                });

            modelBuilder.Entity("MyAcademy.Models.Exam", b =>
                {
                    b.HasOne("MyAcademy.Models.Discipline", "disciplineNavigation")
                        .WithMany("Exams")
                        .HasForeignKey("discipline")
                        .IsRequired()
                        .HasConstraintName("FK_Exams_Disciplines");

                    b.HasOne("MyAcademy.Models.Student", "studentNavigation")
                        .WithMany("Exams")
                        .HasForeignKey("student")
                        .IsRequired()
                        .HasConstraintName("FK_Exams_Students");

                    b.Navigation("disciplineNavigation");

                    b.Navigation("studentNavigation");
                });

            modelBuilder.Entity("MyAcademy.Models.Grade", b =>
                {
                    b.HasOne("MyAcademy.Models.Schedule", "lessonNavigation")
                        .WithMany("Grades")
                        .HasForeignKey("lesson")
                        .IsRequired()
                        .HasConstraintName("FK_Grades_Schedule");

                    b.HasOne("MyAcademy.Models.Student", "studentNavigation")
                        .WithMany("Grades")
                        .HasForeignKey("student")
                        .IsRequired()
                        .HasConstraintName("FK_Grades_Students");

                    b.Navigation("lessonNavigation");

                    b.Navigation("studentNavigation");
                });

            modelBuilder.Entity("MyAcademy.Models.Group", b =>
                {
                    b.HasOne("MyAcademy.Models.Direction", "directionNavigation")
                        .WithMany("Groups")
                        .HasForeignKey("direction")
                        .IsRequired()
                        .HasConstraintName("FK_Groups_Directions");

                    b.Navigation("directionNavigation");
                });

            modelBuilder.Entity("MyAcademy.Models.Salary", b =>
                {
                    b.HasOne("MyAcademy.Models.Teacher", "teacherNavigation")
                        .WithMany("Salaries")
                        .HasForeignKey("teacher")
                        .IsRequired()
                        .HasConstraintName("FK_Salary_Teachers");

                    b.Navigation("teacherNavigation");
                });

            modelBuilder.Entity("MyAcademy.Models.Schedule", b =>
                {
                    b.HasOne("MyAcademy.Models.Discipline", "disciplineNavigation")
                        .WithMany("Schedules")
                        .HasForeignKey("discipline")
                        .IsRequired()
                        .HasConstraintName("FK_Schedule_Disciplines");

                    b.HasOne("MyAcademy.Models.Group", "groupNavigation")
                        .WithMany("Schedules")
                        .HasForeignKey("group")
                        .IsRequired()
                        .HasConstraintName("FK_Schedule_Groups");

                    b.HasOne("MyAcademy.Models.Teacher", "teacherNavigation")
                        .WithMany("Schedules")
                        .HasForeignKey("teacher")
                        .IsRequired()
                        .HasConstraintName("FK_Schedule_Teachers");

                    b.Navigation("disciplineNavigation");

                    b.Navigation("groupNavigation");

                    b.Navigation("teacherNavigation");
                });

            modelBuilder.Entity("MyAcademy.Models.Student", b =>
                {
                    b.HasOne("MyAcademy.Models.Group", "groupNavigation")
                        .WithMany("Students")
                        .HasForeignKey("group")
                        .HasConstraintName("FK_Students_Groups");

                    b.Navigation("groupNavigation");
                });

            modelBuilder.Entity("RequiredDiscipline", b =>
                {
                    b.HasOne("MyAcademy.Models.Discipline", null)
                        .WithMany()
                        .HasForeignKey("discipline")
                        .IsRequired()
                        .HasConstraintName("FK_RequiredDisciplines_Disciplines");

                    b.HasOne("MyAcademy.Models.Discipline", null)
                        .WithMany()
                        .HasForeignKey("required_discipline")
                        .IsRequired()
                        .HasConstraintName("FK_RequiredDisciplines_Disciplines1");
                });

            modelBuilder.Entity("TeachersDisciplinesRelation", b =>
                {
                    b.HasOne("MyAcademy.Models.Discipline", null)
                        .WithMany()
                        .HasForeignKey("discipline")
                        .IsRequired()
                        .HasConstraintName("FK_TeachersDisciplinesRelation_Disciplines");

                    b.HasOne("MyAcademy.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("teacher")
                        .IsRequired()
                        .HasConstraintName("FK_TeachersDisciplinesRelation_Teachers");
                });

            modelBuilder.Entity("MyAcademy.Models.Direction", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("MyAcademy.Models.Discipline", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("MyAcademy.Models.Group", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("MyAcademy.Models.Holiday", b =>
                {
                    b.Navigation("DaysOFFs");
                });

            modelBuilder.Entity("MyAcademy.Models.Schedule", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("MyAcademy.Models.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Exams");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("MyAcademy.Models.Teacher", b =>
                {
                    b.Navigation("Salaries");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
